# Generated by Django 4.1.2 on 2022-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriale', models.CharField(max_length=50)),
                ('codice_interno', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=254)),
                ('installazione', models.DateField()),
                ('tipologia', models.CharField(choices=[('fisso', 'fisso'), ('portatile', 'portalile'), ('dismesso', 'dismesso')], default=1, max_length=100)),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Computer',
            },
        ),
    ]
