# Generated by Django 4.1.2 on 2022-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giacenze', '0002_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
