# Generated by Django 4.1.2 on 2022-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giacenze', '0003_alter_pc_note_alter_telefono_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
