# Generated by Django 4.1.2 on 2022-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giacenze', '0004_alter_pc_note_alter_telefono_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periferiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('quantita', models.IntegerField(default=1)),
            ],
        ),
    ]
